### ISSUE TITLE
Percentile

### ISSUE THREAD

**Issue by zackspica** [ThomasLecocq/ssxm#1]
Hi Thom, 

I just used your code and works great except for the percentiles option. At line 88: P = Percentile(percentile=perc) - I think an import is missing for the Percentile function.

**Comment by ThomasLecocq** [comment]
Hey, what's the traceback of the error? The Percentile func is in the same file, but it could be that it's still using an old implementation from scipy

**Comment by zackspica** [comment]
My bad I was too quick in opening this issue... I found my silly mistake right after... :)
